# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [34]:
import numpy as np

In [35]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

## Creating arrays


In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [39]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [40]:
a[2] = 10

In [41]:
a

array([ 1,  2, 10,  5,  7, 12])

In [42]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.linspace(0, 12, 13)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## Multi-dimensional arrays


In [44]:
np.ones((6, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [46]:
n[0, 2] = 20

In [47]:
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [48]:
n[2] = [1, 1, 1]

In [49]:
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [50]:
n[:, 2] = [3, 3, 3]

In [51]:
n

array([[1, 2, 3],
       [4, 5, 3],
       [1, 1, 3]])

## Randomly generated arrays


In [59]:
np.random.seed(2)
10000*np.random.rand(5, 2)

array([[4359.94902142,  259.26231828],
       [5496.62477879, 4353.22392618],
       [4203.67802087, 3303.34821004],
       [2046.48634038, 6192.70966351],
       [2996.54673675, 2668.27275103]])

In [60]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [61]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [67]:
a = (a + 67)*2
a

array([270, 272, 274, 276, 278])

In [68]:
b = (10 + (a * 2)) ** 2 / 100

In [69]:
b

array([3025.  , 3069.16, 3113.64, 3158.44, 3203.56])

In [70]:
a / b + 10

array([10.0892562 , 10.0886236 , 10.0879999 , 10.08738491, 10.08677846])

In [71]:
c=a+b
c

array([3295.  , 3341.16, 3387.64, 3434.44, 3481.56])

## Comparison operations

In [72]:
a

array([270, 272, 274, 276, 278])

In [74]:
a >= 272

array([False,  True,  True,  True,  True])

In [75]:
b

array([3025.  , 3069.16, 3113.64, 3158.44, 3203.56])

In [78]:
a < b

array([ True,  True,  True,  True,  True])

In [80]:
b[a < b]

array([3025.  , 3069.16, 3113.64, 3158.44, 3203.56])

## Summarizing operations

In [81]:
a

array([270, 272, 274, 276, 278])

In [83]:
a.min()

np.int64(270)

In [84]:
a.max()

np.int64(278)

In [82]:
a.std()

np.float64(2.8284271247461903)

In [33]:
n.min()

np.int64(1)

### Next

Linear algebra refresher