In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [6]:
>>> np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
>>> np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
>>> np.full(10, 67)

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [10]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[4]

np.int64(7)